version: '3.7'

services:
  
  php:
    image: php:7.1-cli
    working_dir: /code
    volumes:
      - .:/code
    networks: 
      - default
    command: bash

networks:
  default:
    name: ${DOCKER_DEFAULT_NETWORK}